### PR TITLE
Add Kopy SNAPSHOT version

### PR DESCRIPTION
**Pull request by JavierSegoviaCordoba**
Add Kopy SNAPSHOT version and the Sonatype Maven snapshots repository

### CODE REVIEW

**Comment by JavierSegoviaCordoba** [comment]
@sureshg running `./gradlew assemble` works on Windows. Can you check if it works on ARM?

To be sure the last Kopy SNAPSHOT dependency is added, use:

```shell
./gradlew assemble --refresh-dependencies
```

**Comment by sureshg** [comment]
same error - More details here - https://github.com/JavierSegoviaCordoba/kopy/issues/37#issuecomment-2336777145

**Comment by JavierSegoviaCordoba** [comment]
It is a bit weird, it is only looking for it on the Gradle Plugin Portal.

I have tried to add all repositories, including the snapshots one, to the `repositories` block in the `build.gradle.kts` inside `build-logic` but it is still ignored.

I am going to do a release with the `0.11.0-2.0.20` so you can test it directly.

**Comment by JavierSegoviaCordoba** [comment]
It will be published in this job, it should be on Maven Central around 10 minutes later.

https://github.com/JavierSegoviaCordoba/kopy/actions/runs/10762188392

**Comment by sureshg** [comment]
hmmm..same issue
```
> Task :build-logic:checkKotlinGradlePluginConfigurationErrors
Download https://repo.maven.apache.org/maven2/com/javiersc/kotlin/kopy-gradle-plugin/0.11.0+2.0.20/kopy-gradle-plugin-0.11.0+2.0.20.pom, took 444 ms
Download https://repo.maven.apache.org/maven2/com/javiersc/kotlin/kopy-gradle-plugin/0.11.0+2.0.20/kopy-gradle-plugin-0.11.0+2.0.20.module, took 102 ms
Download https://repo.maven.apache.org/maven2/com/javiersc/kotlin/kopy-args/0.11.0+2.0.20/kopy-args-0.11.0+2.0.20.pom, took 115 ms
Download https://repo.maven.apache.org/maven2/com/javiersc/kotlin/kopy-args/0.11.0+2.0.20/kopy-args-0.11.0+2.0.20.module, took 114 ms
Download https://repo.maven.apache.org/maven2/com/javiersc/kotlin/kopy-args/0.11.0+2.0.20/kopy-args-0.11.0+2.0.20.jar, took 113 ms
Download https://repo.maven.apache.org/maven2/com/javiersc/kotlin/kopy-gradle-plugin/0.11.0+2.0.20/kopy-gradle-plugin-0.11.0+2.0.20.jar, took 392 ms
> Task :build-logic:generateExternalPluginSpecBuilders
> Task :build-logic:generateJte UP-TO-DATE
> Task :build-logic:extractPrecompiledScriptPluginPlugins UP-TO-DATE
> Task :build-logic:compilePluginsBlocks
> Task :build-logic:generatePrecompiledScriptPluginAccessors
> Task :build-logic:generateScriptPluginAdapters UP-TO-DATE
> Task :build-logic:pluginDescriptors UP-TO-DATE
> Task :build-logic:processResources UP-TO-DATE
> Task :build-logic:compileKotlin
> Task :build-logic:compileJava NO-SOURCE
> Task :build-logic:classes UP-TO-DATE

> Task :build-logic:jar
:jar: A valid plugin descriptor was found for com.gradle.develocity.properties but the implementation class com.gradle.develocity.agent.gradle.DevelocityPlugin was not found in the jar.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all artifacts for configuration 'classpath'.
> Could not find com.javiersc.kotlin:kopy-gradle-plugin:0.11.0+2.0.20.
  Searched in the following locations:
    - https://plugins.gradle.org/m2/com/javiersc/kotlin/kopy-gradle-plugin/0.11.0+2.0.20/kopy-gradle-plugin-0.11.0+2.0.20.pom
  Required by:
      unspecified:unspecified:unspecified > project :build-logic

* Try:
> If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

CONFIGURE FAILED in 25s
```

**Comment by JavierSegoviaCordoba** [comment]
I don't know why it is not found 😕

If you open the next link:

https://plugins.gradle.org/m2/com/javiersc/kotlin/kopy-gradle-plugin/0.11.0+2.0.20/

You will find that it contains the associated POM file `copy-gradle-plugin-0.11.0+2.0.20.pom`

It looks the same as your project does not find.

```diff
-https://plugins.gradle.org/m2/com/javiersc/kotlin/kopy-gradle-plugin/0.11.0+2.0.20/kopy-gradle-plugin-0.11.0+2.0.20.pom
+https://plugins.gradle.org/m2/com/javiersc/kotlin/kopy-gradle-plugin/0.11.0+2.0.20/kopy-gradle-plugin-0.11.0+2.0.20.pom
```

What is weird to me, is that inside your project Gradle is only looking at the Gradle Plugin Portal, but you are specifying more repositories that are ignored.

**Comment by JavierSegoviaCordoba** [comment]
Another try you can do is using the marker one, but I would bet you will get the same issue:

- `com.javiersc.kotlin.kopy:com.javiersc.kotlin.kopy.gradle.plugin:0.11.0+2.0.20`

**Comment by sureshg** [comment]
More info: https://github.com/JavierSegoviaCordoba/kopy/issues/37#issuecomment-2336836394

**Pull request merged**
